formatter: "markdown table"

recursive:
  enabled: true

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: required

settings:
  anchor: true
  hide-empty: true
  lockfile: false
  read-comments: true
