#!/bin/bash
export TFE_TOKEN="GSbtyclMI6bPRg.atlasv1.T9JT1amV7NwIJgRKyz8neyiJMDebbts4Uqm0M8v4m94hxeNtmkocFHVND8tzdWvjijw"
export VAULT_TOKEN="hvs.CAESIMb36xxEgqIgTaTxSLXroWhzq2OH3GCIgkBBUkP7VmpSGikKImh2cy50cDkwQVo0aWs2VHFnWDQwcmxlb1lONEUueEJNSlAQkIv6Cg"
terraform apply -auto-approve > apply.log 2>&1
